In [5]:
class Domain:
    def __init__(self) -> None:
        self.value = 4
    
    def increment_time(self):
        self.value += 1

class Field:
    def __init__(self,d) -> None:
        self.domain = d


d = Domain()

d.step_time()

d.value
d.step_time()

d.value

6

In [31]:
import numpy as np
import numexpr

result = numexpr.evaluate("a+b",{"a":np.array([[4,5],[5,6]]),\
                                "b":np.array([[4,5],[5,6]])})
print(result)
axes = ("b","a")

data = np.array([[3,4],[5,6]])


def idxs_tuple(idxs):

    idxs_filled = dict()

    for axis in axes:
        if axis not in idxs.keys():
            idxs_filled[axis] = slice(None)
        else:
            idxs_filled[axis] = idxs[axis]

    print(idxs_filled)



    return tuple(idxs_filled[axis] for axis in axes)


def get(idxs):

    return data[idxs_tuple(idxs)]


def set(idxs,values):
    # used for: setting to values for an expression (initial conditions)
    # setting boundary condition, constant array would be constructed
    # updating timestep
    data[idxs_tuple(idxs)] = values



def set_expression(idxs,expression):
    numexpr

idxs_tuple({})



[[ 8 10]
 [10 12]]
{'b': slice(None, None, None), 'a': slice(None, None, None)}


(slice(None, None, None), slice(None, None, None))

In [27]:

def transpose(nested_list):
    transposed_list = [[row[i] for row in nested_list] for i in range(len(nested_list[0]))]
    return transposed_list
import itertools

substitute_axes_values = [[3,4],[5,6]]

value_combs = transpose([list(comb) for comb in itertools.product(*substitute_axes_values)])

value_combs

[[3, 3, 4, 4], [5, 6, 5, 6]]

In [35]:
np.reshape([3,4,5,6,7,8],[2,3])

np.zeros([3,4],dtype="object")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=object)

In [38]:
np.full((3,4),0,dtype="object")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=object)