In [28]:
import numpy as np

from scipy import signal

A = np.full((4,5,10),1)

A[-1]

M = np.zeros((1,10,10))

k1 = np.zeros((1, 1, 3))

vals = [1,-2,1]
kernel = np.array(vals).reshape((1,1,3))

k2 = np.zeros((1, 3, 1))

A = signal.convolve(M,k2,mode='valid')

print(A)

kernel

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


array([[[ 1, -2,  1]]])

In [9]:
import time
import numpy as np
from scipy import signal
from scipy import ndimage

vals = np.matrix([[1,-2,1]])

#data = np.linspace(0,1,10**8)**3

data = np.ones((100,100))


n_times = 1000



start = time.time()

for i in range(n_times):
    a = signal.convolve(data,vals,mode='valid')

mid = time.time()

for i in range(n_times):
    new = data[2:]-2*data[1:-1]+data[0:-2]





end = time.time()



convolve_time = mid-start
simple_time = end-mid

print(convolve_time/simple_time)





54.28317121541222


In [54]:
import numpy as np

# TODO expand this to multiple dimensions

kernel = {-1:3,  0:1,    1:2}

data = np.array([3,4,8,9,2,1,5])

pairs = zip(kernel,kernel.values())

shifts = list(kernel.keys())

min_shift = shifts[0]
max_shift = shifts[-1]


new_length = len(data)+min_shift-max_shift

diff_data = np.zeros((1,new_length))

for pair in pairs:
    shift = pair[0]
    weight = pair[1]

    upper = shift-max_shift

    if upper==0:
        upper = data.size

    component = weight*data[shift-min_shift:upper]
    print(component)
    diff_data+= component
data[1:-1]
data[shift-min_shift:shift-max_shift]

[ 9 12 24 27  6]
[4 8 9 2 1]
[16 18  4  2 10]


array([], dtype=int32)

In [55]:

import numpy as np

class Unknown:
    def __init__(self) -> None:
        pass
    def __repr__(self) -> str:
        return "?"


periodic = False

a = np.array([[0,1,2,3,4,5],[0,1,2,3,4,5],[0,1,2,3,4,5]],dtype="object")**3+10

kernel = {-1:1,  0:-2,    1:1}

kernel_axis = 0



n_axes = len(a.shape)


kernel_axis_len = a.shape[kernel_axis]

shifts = list(kernel.keys())
weights = list(kernel.values())

diff = np.zeros(a.shape,dtype="object")

for i in range(len(kernel)):
    diff+=weights[i]*np.roll(a,shifts[i],axis=kernel_axis)

left_cut = -shifts[0]
right_cut = shifts[-1]

print(diff)

start_idxs = [slice(None)]*n_axes
start_idxs[kernel_axis] = slice(0,left_cut)

end_idxs = [slice(None)]*n_axes
end_idxs[kernel_axis] = slice(kernel_axis_len-right_cut,kernel_axis_len)


# instead of cutting it replace the extra ones with Unknowns
if not periodic:
    
    diff[tuple(start_idxs)] = Unknown()
    diff[tuple(end_idxs)] = Unknown()

diff

diff

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


array([[?, ?, ?, ?, ?, ?],
       [0, 0, 0, 0, 0, 0],
       [?, ?, ?, ?, ?, ?]], dtype=object)

In [32]:
import numpy as np

def get_values_at_index(array, index, dimension):
    # Get the shape of the array
    shape = array.shape

    # Create an indexing tuple to access the desired elements
    indexing_tuple = [slice(None)] * len(shape)
    indexing_tuple[dimension] = slice(0,index)

    print(indexing_tuple)
    # Use the indexing tuple to access the elements at the specified index
    values = array[tuple(indexing_tuple)]

    return values



# Create a 3-dimensional numpy array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
# Get the values at index 1 along dimension 0
result = get_values_at_index(arr, 1, 1)

print(result)  # Output: [[5 6]
               #          [7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[slice(None, None, None), slice(0, 1, None), slice(None, None, None)]
[[[1 2]]

 [[5 6]]]


In [6]:
import numpy as np
a = np.zeros((3,1))
b = np.array([3,2,5,6])
b[-2]

5